### ISSUE TITLE
mention DO_NOT_TRACK=1

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#1]
see the effort at:
https://consoledonottrack.com/
https://github.com/sneak/consoledonottrack.com

**Comment by beatcracker** [comment]
Thanks for bringing this project to my attention! I'm not sure how I missed this proactive effort before.

I've added a link to the readme and I plan to expand telemetry definitions with examples mention on their site.

**Comment by emanuelb** [comment]
Great :) you can see more info for some of the definitions in:
https://github.com/sneak/consoledonottrack.com/issues/2
see also the discussion about "Awesome Do Not Track List" as your project does in:
https://github.com/sneak/consoledonottrack.com/issues/8
