### ISSUE TITLE
Add 11 Env Variables from OptOutEnv repo

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#12]
Here CSV with details about the ENV vars:
https://github.com/rljacobson/OptOutEnv/blob/main/OotOutEnvDB.csv

Found this project by searching in reddit:
https://www.reddit.com/r/privacy/comments/jos01i/my_personal_database_of_telemetry_optout/

it contain 11 Env Variables not in this project:

> UPLOAD_ENABLED
CONTRAST_DOTNET_TELEMETRY_OPTOUT
BUCKAROO_TELEMETRY_OPT_OUT
GROUPAROO_TELEMETRY_ENABLED
JSDEFENDER_TELEMETRY_OPT_OUT
COYOTE_CLI_TELEMETRY_OPTOUT
VCPKG_DISABLE_METRICS
NEXT_TELEMETRY_DEBUG
UNO_PLATFORM_TELEMETRY_OPTOUT
DOTNET_HTTPREPL_TELEMETRY_OPTOUT
ET_NO_TELEMETRY

Also worth to add issue in the repo: https://github.com/rljacobson/OptOutEnv to tell them about this project which is more mature.

**Comment by beatcracker** [comment]
Thanks for your support, keep the issues coming 😉 . I'll do my best to integrate all the stuff you've found.

**Comment by emanuelb** [comment]
I opened separate issue with more information for each env var in this issue, thus closing this issue.
1. UPLOAD_ENABLED https://github.com/beatcracker/toptout/issues/143
2. CONTRAST_DOTNET_TELEMETRY_OPTOUT https://github.com/beatcracker/toptout/issues/142
3. BUCKAROO_TELEMETRY_OPT_OUT https://github.com/beatcracker/toptout/issues/141
4. GROUPAROO_TELEMETRY_ENABLED https://github.com/beatcracker/toptout/issues/140
5. JSDEFENDER_TELEMETRY_OPT_OUT & PJSD_TELEMETRY_OPT_OUT https://github.com/beatcracker/toptout/issues/133
6. COYOTE_CLI_TELEMETRY_OPTOUT https://github.com/beatcracker/toptout/issues/139
7. VCPKG_DISABLE_METRICS https://github.com/beatcracker/toptout/issues/138
8. NEXT_TELEMETRY_DEBUG https://github.com/beatcracker/toptout/issues/137
9. UNO_PLATFORM_TELEMETRY_OPTOUT https://github.com/beatcracker/toptout/issues/136
10. DOTNET_HTTPREPL_TELEMETRY_OPTOUT https://github.com/beatcracker/toptout/issues/135
11. ET_NO_TELEMETRY https://github.com/beatcracker/toptout/issues/134
