### ISSUE TITLE
Add script to disable all mentioned telemetry

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#2]
something like the below script:
https://gist.github.com/sneak/c6845e95a9308a65ea3d29422f5a92ac
just more complete, which include all programs described in this repo.

**Comment by beatcracker** [comment]
I actually plan to release a cli tool that would do exactly that: run on your system and configure all known telemetry channels. Meanwhile, it's pretty easy to generate shell scripts using [existing data](https://github.com/beatcracker/toptout/tree/master/data) so I might as well do this sometime soon.
