### ISSUE TITLE
Twitter account is temporarily restricted

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#238]
Visiting https://twitter.com/toptout_me (authenticated or in private mode) return:

Caution: This account is temporarily restricted
You’re seeing this warning because there has been some unusual activity from this account. Do you still want to view it?

Searching twitter return this article "Help with locked or limited account":
https://help.twitter.com/en/managing-your-account/locked-and-limited-accounts

![ToptoutRestricted](https://user-images.githubusercontent.com/1792055/120155600-ad184b00-c1f9-11eb-80c1-fb4ad5004d53.png)

**Comment by beatcracker** [comment]
Yeah, and I can't post anything:
> This request looks like it might be automated. To protect our users from spam and other malicious activity, we can’t complete this action right now. Please try again later.

No idea why and how to fix: linked article is no help - I don't get a captcha or anything like that. Meh...

**Comment by emanuelb** [comment]
I have some kinda guesses of why this happening after reading on twitter help site:
1. you using some private network to accsses twitter (Tor / VPNs, etc...) which is shame if twitter block/fight them,
2. your account password/email was reported as being hacked? or something related, such as results from sites like https://monitor.firefox.com/
3. my fault :( trying to promote the project by reply tweeting to relevant tweets which had some success (likes + github follower) but also unfortunately 1 accusing of spamming which I don't know maybe reported the user?! or some twitter AI/ML auto stuff did it?

Still not sure at all, maybe something else...

is there any information in the account why it's happening? or how to contact twitter support which is likely the next needed step, probably using this form: (for suspended or locked accounts)
https://help.twitter.com/forms/general?subtopic=suspended

There also article "About suspended accounts" which link to above "Help with locked or limited account":
https://help.twitter.com/en/managing-your-account/suspended-twitter-accounts

**Comment by beatcracker** [comment]
Fixed.

> Hello,
>
>We’re writing to let you know that your account is now unlocked. We’re sorry for the inconvenience.
>
>A little background: We have systems that find and remove automated spam Twitter accounts, and it looks like yours was flagged as spam by mistake. This can happen if an account exhibits automated behavior in violation of our rules.
>
>We apologize for the mixup, and hope to see back on Twitter soon. 
>
>If you need to get in touch with us again, please file a report through your Twitter app or our [forms page](https://help.twitter.com/forms), as this account isn’t monitored for replies. 
>
>Thanks,
>
>Twitter
