### ISSUE TITLE
Add Appc Daemon

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#26]
https://github.com/appcelerator/appc-daemon/blob/b88704da667605f1d5f73cfd0d07b928ef9b876a/docs/Environment%20Variables.md#environment-variables

Env var: `APPCD_TELEMETRY` | Controls the telemetry system. Set to `0` or `false` to disable telemetry. Defaults to true

**Comment by beatcracker** [comment]
Closed via cde7e85
