### ISSUE TITLE
Add serverless

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#27]
https://github.com/serverless/serverless/blob/master/docs/telemetry.md#disabling-telemetry
to disable: set env var `SLS_TELEMETRY_DISABLED=1`

There is also undocumented `SLS_TRACKING_DISABLED` env var in code, which is mentioned in pr: https://github.com/serverless/serverless/pull/6867

> To make opting out from tracking easier (in test runs) introduce `SLS_TRACKING_DISABLED` env variable

**Comment by beatcracker** [comment]
Closed via b0206b1
