### ISSUE TITLE
Add nvidia drivers data

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#3]
Nvidia driver on windows come with not needed service "NvTelemetryContainer", more info:
https://www.ghacks.net/2016/11/07/nvidia-telemetry-tracking/
someone posted commands to disable this service and other related scheduled tasks at:
https://www.reddit.com/r/privacy/comments/gmwlv5/do_nvidia_drivers_include_telemetry_or_other/fr6lieg/

```batch
sc stop "NvTelemetryContainer"

sc config "NvTelemetryContainer" start=disabled

schtasks /change /disable /tn "NvTmMon_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}"

schtasks /change /disable /tn "NvTmRep_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}"

schtasks /change /disable /tn "NvTmRepOnLogon_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}"
```

The picture in old tool at:
https://github.com/NateShoffner/Disable-Nvidia-Telemetry
show that another scheduled tasks need to be disabled & modification needed for registery key, looks like it's handled by code in:
https://gist.github.com/alex-anenkov/8d6c9bfef9b0142ced8dabfbb5d5db61#file-fuck_telemetry-cmd-L67-L76

**Comment by beatcracker** [comment]
It deserves a mention, sure. I'll see what I can do, but as with Windows - no promises about unofficial stuff.
