### ISSUE TITLE
Add Quilt

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#31]
https://docs.quiltdata.com/api-reference/cli#quilt_disable_usage_metrics
https://github.com/quiltdata/quilt/blob/version-3.4.x/docs/API%20Reference/cli.md#quilt_disable_usage_metrics
disable via env var `QUILT_DISABLE_USAGE_METRICS=true`

**Comment by beatcracker** [comment]
Closed via 5f4e265
