### ISSUE TITLE
Add .NET Interactive

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#34]
https://github.com/dotnet/interactive/blob/cc06740d584677b76a9ab07f496072642621aac2/docs/README.md#how-to-opt-out

The .NET Interactive telemetry feature is enabled by default. To opt out of the telemetry feature, set the `DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT` environment variable to `1` or `true`

**Comment by beatcracker** [comment]
Closed via 38999c4
