### ISSUE TITLE
Add dotnet-svcutil

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#36]
https://github.com/dotnet/wcf/blob/0d1b3d9460993fa6d4371943e74b25710343b7a4/release-notes/dotnet-svcutil-notes.md#104-10302018

> Added anonymous telemetry information collection (set environment variable `DOTNET_SVCUTIL_TELEMETRY_OPTOUT=1` to opt out).

**Comment by beatcracker** [comment]
Closed via 90b3b9d
