### ISSUE TITLE
Add Windows OS data

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#4]
Windows 10 come with lot of telemetry which can't be fully disabled on non education or enterprise editions, there are many tools/scripts which try to disable as much as possible the telemetry on windows (some scripts contain data for other tools, such as visual studio or MS office)
https://www.ghacks.net/2015/08/14/comparison-of-windows-10-privacy-tools/
https://github.com/mirinsoft/debotnet
https://github.com/10se1ucgo/DisableWinTracking
https://github.com/hahndorf/Set-Privacy
https://github.com/MichiMunich/Windows10-Privacy
https://gist.github.com/alirobe/7f3b34ad89a159e6daa1
https://github.com/undergroundwires/privacy.sexy/blob/master/src/application/application.yaml
https://gist.github.com/alex-anenkov/8d6c9bfef9b0142ced8dabfbb5d5db61

**Comment by beatcracker** [comment]
I plan to mention Windows telemetry, but it's hard to keep track of all unofficial ways to disable it. It's an uphill battle and anything beyond [using Registry Editor to set the diagnostic data level](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#use-registry-editor-to-set-the-diagnostic-data-level) will be probbaly obsoleted quickly. So, no promises.
