### ISSUE TITLE
Add env var SFDX_DISABLE_INSIGHTS

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#41]
https://github.com/forcedotcom/cli-packages/blob/b089ff3508131aa35774ee088376b7a98dcb3167/packages/telemetry/README.md#env-variables
`SFDX_DISABLE_INSIGHTS`: Set to true if you want to disable telemetry.

**Comment by beatcracker** [comment]
https://github.com/forcedotcom/cli/issues/194#issuecomment-580839345
> There has been an update, the env var is SFDX_DISABLE_TELEMETRY

So this should be covered by 9cd839f /#16
