### ISSUE TITLE
PowerShell: Delete file DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY if exists

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#42]
https://github.com/PowerShell/PowerShell-RFC/blob/ab39d5245130ac60690399d70190aa3ab864faf9/5-Final/RFC0016-Census-Telemetry.md#specification

Telemetry is only collected if the file `DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY` exists in `$PSHome`

From github search, some scripts do:
```shell
            rm /opt/microsoft/powershell/*/DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY
```

also from docs of "What's New in PowerShell Core 6.1":
https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-61.md#telemetry-can-only-be-disabled-with-an-environment-variable

To opt-out of this telemetry, set the environment variable `POWERSHELL_TELEMETRY_OPTOUT` to true, yes, or 1. We no longer support deletion of the file `DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY` to disable telemetry.

so looks like it's the method for disable telemetry for old powershell?

**Comment by beatcracker** [comment]
Yep, it's for v6.x and given their release cadence, it's pretty outdated. Current release is v7.1.3 so I think we can ignore this.

**Comment by emanuelb** [comment]
Maybe mark stuff that is for old versions with versions affected (like powershell < 6.1), script to disable can run something like:
```php
if(powershell_version_installed < 6.1) { 
echo "powershell-is-old, better to upgrade, disable telemetry via file deletion"; 
rm DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY; }
```

**Comment by beatcracker** [comment]
It's not possible to express using current schema, but I'll add this as a `noop` target to the [powershell-core.json](https://github.com/beatcracker/toptout/blob/master/data/powershell-core.json) with note about PowerShell version.
