### ISSUE TITLE
Add env var HOMEBREW_NO_AUTO_UPDATE

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#425]
https://github.com/Homebrew/brew/blob/b18bbacced4a23df8b2e6a57b7a2bded45fc2a77/docs/Manpage.md
- `HOMEBREW_NO_AUTO_UPDATE`
  If set, do not automatically update before running some commands e.g. `brew install`, `brew upgrade` and `brew tap`.

**Comment by beatcracker** [comment]
- [data/homebrew.json](https://github.com/beatcracker/toptout/blob/master/data/homebrew.json)
