### ISSUE TITLE
Add env var YARN_ENABLE_TELEMETRY

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#429]
https://github.com/yarnpkg/berry/blob/8afcaa2a954e196d6cd997f8ba506f776df83b1f/packages/acceptance-tests/pkg-tests-core/sources/utils/makeTemporaryEnv.ts#L45
https://github.com/ourchitecture/panda/blob/54aabbd9e3ea8947627b25d59e1fd7e0e8728fec/src/docker/devops/node/Dockerfile#L6

**Comment by beatcracker** [comment]
Notes: https://github.com/yarnpkg/berry/issues/1780#issuecomment-683693375
Update: [data/yarn2.json](https://github.com/beatcracker/toptout/blob/master/data/yarn2.json)
