### ISSUE TITLE
Add Feast

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#43]
https://github.com/feast-dev/feast/blob/63db0e367aa10fec41fb34a78ab758953bc1d759/docs/feast-on-kubernetes/advanced-1/telemetry.md#how-to-disable-telemetry

To opt out of telemetry, simply set the environment variable `FEAST_TELEMETRY` to `False` in the environment in which the Feast client is run.

**Comment by beatcracker** [comment]
Closed via 2f3e792
