### ISSUE TITLE
Windows script toptout_pwsh.ps1 is broken

### ISSUE THREAD

**Issue by cyberlytics** [beatcracker/toptout#446]
Thanks for your great work!

Now to the issue at hand:
Current Windows script toptout_pwsh.ps1 is broken.
It does not execute but results in an error.

The reason is line 207:
Set-EnvVar -Name 'TELEMETRY_OPT_IN' -Value '' -ShowLog:$ShowLog

1) Your Function Set-EnvVar does not support empty or null values. (For good reasons, as we will see next!)

2) If we would fix the function Set-EnvVar to allow empty strings then it would not work as intended either: [System.Environment]::SetEnvironmentVariable($Name, '')  would NOT set the variable to an empty string but would DELETE the environment variable! (This would not be intended for TELEMETRY_OPT_IN.) Please cf. to https://ss64.com/ps/syntax-env.html for this windows behaviour. Is there any way to set an environment variable via PowerShell to an empty string? Not to my knowledge! This is a known crazy fucked up situation by Microsoft.

Suggestion: remove lines 201-208 from the script, or replace 207 with a TODO entry.
This would be better than let it remain broken.

Again: Thank for your great work!

Kind regards
Christoph

**Comment by beatcracker** [comment]
Thanks, I'll see what I can do. Looks like this is [canvas-lms.json#L62](https://github.com/beatcracker/toptout/blob/d6d84f5f5d0a585b6933daeb4ffe886b6f7a51e0/data/canvas-lms.json#L62) giving us trouble. Fortunately, deleting env. var is exactly what we need here, so this should be easy to fix.

**Comment by beatcracker** [comment]
Looks like the scripts were also broken by 2e9227a64978eacf85917ac5c5cd2f53521a4b1e :disappointed_relieved: .
I've pushed a fix for both of these issues: see if it works for you and feel free to re-open or create a new issue if you find anything else broken

**Comment by cyberlytics** [comment]
Perfect! Works like a charm.
Thank you!
