### ISSUE TITLE
Add FireFox data

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#5]
FireFox based browsers (FireFox / Firefox Developer Edition) contain telemetry which can be disabled, see:
https://www.howtogeek.com/557929/how-to-see-and-disable-the-telemetry-data-firefox-collects-about-you/
see below script: (search for 'telemetry'):
https://github.com/ghacksuserjs/ghacks-user.js/blob/05580f5e99ccbe02646c9062acd137e51b55a8d2/user.js#

**Comment by beatcracker** [comment]
Thanks, this is something that would definitely like to add.

**Comment by beatcracker** [comment]
Finally!

* https://github.com/beatcracker/toptout#firefox

Had to add a lot of stuff to support it, that's why it took so long.
