### ISSUE TITLE
Add Warp

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#519]
https://www.warp.dev/privacy

> Telemetry
When Warp comes out of beta, telemetry will be opt-in and anonymous.
But for our beta phase, we do send [telemetry](https://docs.warp.dev/getting-started/privacy#exhaustive-telemetry-table) by default and we do associate it with the logged in user because it makes it much easier to reach out and get feedback when something goes wrong.

https://docs.warp.dev/getting-started/privacy

> Telemetry: What usage data are you collecting and why?
For our public beta, we collect usage data (only metadata never console input or output) to measure feature usage, discover product friction, and improve Warp by guiding what we prioritize. See below for an exhaustive list of the metadata we collect.
When Warp comes out of beta and enters General Availability, telemetry will be opt-in and anonymous.

**Comment by beatcracker** [comment]
Uses Segment.io : https://github.com/warpdotdev/Warp/issues/1346
