### ISSUE TITLE
Introduce a shell script with disabled telemetry for everything

### ISSUE THREAD

**Issue by ligurio** [beatcracker/toptout#625]
List on https://toptout.me/ describes steps how to disable telemetry for different applications.
However, there is no single env variable that will be supported by all or most part of applications (like `NO_COLOR` [^1]) and telemetry should be disabled separately for every application.

I suggest introducing a shell script that could be sourced to `.profile` and thus will disable telemetry for everything described in toptout.me. Like this:

```bash
...
HOMEBREW_NO_ANALYTICS_THIS_RUN=1
HOMEBREW_NO_ANALYTICS=1
LYNX_ANALYTICS=1
...
```

[^1]: http://no-color.org/

**Comment by beatcracker** [comment]
Have a look at [./examples](https://github.com/beatcracker/toptout/tree/master/examples), should be exactly what you're looking for 🤗.  Do you have ideas on how this can be made more discoverable?

**Comment by ligurio** [comment]
> Have a look at [./examples](https://github.com/beatcracker/toptout/tree/master/examples), should be exactly what you're looking for 🤗.

Oh, very nice! This is exactly what I need.

> Do you have ideas on how this can be made more discoverable?

I have no idea why I have overlooked it. It is a third bullet in the README [^1]  :man_facepalming: 

[^1]: https://github.com/beatcracker/toptout#-scripts

**Comment by ligurio** [comment]
@beatcracker thanks for the project!
