### ISSUE TITLE
Add ember-cli

### ISSUE THREAD

**Issue by emanuelb** [beatcracker/toptout#8]
more info at:
https://github.com/ember-cli/ember-cli/blob/master/docs/analytics.md#still-not-comfortable

seen below `.ember-cli` content in project:
```js
{
  /**
    Ember CLI sends analytics information by default. The data is completely
    anonymous, but there are times when you might want to disable this behavior.

    Setting `disableAnalytics` to true will prevent any data from being sent.
  */
  "disableAnalytics": false
}
```

setting to true will disable it in project `.ember-cli` file (or `$HOME/.ember-cli` for user-wide)

**Comment by beatcracker** [comment]
Thanks, added!
